### PR TITLE
fix invisible Adapter-Dome-Half-Framed-M

### PR DESCRIPTION
**Pull request by Gordon-Dry**

### CODE REVIEW

**Comment by Gordon-Dry** [comment]
This fixes https://github.com/KSP-RO/ROTanks/issues/2

**Comment by Gordon-Dry** [comment]
I guess I should post screenshots of my fixed game showing both dome variants of nose and mount, so a total of 4 screenshots.
Will follow soon.

**Comment by Gordon-Dry** [comment]
So, both variants say "framed", I'm not sure if the M variant is really fixed ... it's not invisible anymore though.

Dome-Framed-M
screenshot_2019-07-03--00-15-39

Dome-Framed-S
screenshot_2019-07-03--00-18-11

**Comment by Gordon-Dry** [comment]
Just to make that clear:
that fixes the issue

Anybody else can confirm that?

**Comment by gazpachian** [comment]
@Gordon-Dry Your solution is _A_ solution, but I figured it out. Dome-Half-Framed-N is the model that appears as Dome-Half in the selection, so your solution is simply patching that in where something else should be. I grabbed a fresh copy of SSTU and found the missing Framed-N model in there, which for comparison's sake looks like the top dome here: 

Dome-M and Dome-N

At the bottom is the regular dome-half for comparison (which is what the missing dome looks like in your fix), clearly distinguishable from the upper option. Grab the model yourself from my PR but make sure to revert the changes in this PR for it to have an effect when you test it. 

I believe this pull request should be closed and mine merged, but all credit to you for making me test things out! No matter what, one thing we can all agree on is that SSTUs naming convention is _at most_ half as good as the actual mod itself. ;)

**Pull request closed without merging**
